# Generated by Django 5.0.6 on 2024-05-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.TextField(blank=True, default=None, help_text='Ссылка на видео', null=True, verbose_name='Видео'),
        ),
    ]
