# Generated by Django 5.0.6 on 2024-05-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('date',), 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
