# Generated by Django 5.0.6 on 2024-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, default=None, help_text='Ссылка на видео', null=True, verbose_name='Видео'),
        ),
    ]
