# Generated by Django 5.0.6 on 2024-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='session_id'),
        ),
    ]
